#!/usr/bin/env node

console.log("\x1b[1;33mtongong's node calculator script\x1b[0m")
console.log("  - basic Javascript math functions");
console.log("  - functions from the JS Math module");
console.log("  - s(x): shorthand for sqrt(x)");
console.log("  - l(x): shorthand for console.log(x)");

r=require('repl').start({prompt:'> '}).context;

Object.getOwnPropertyNames(Math).forEach(a=>{r[a]=Math[a]});
r.s = r.sqrt;
r.l = console.log
