#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extention or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

case "$ext" in
	# Try to keep these cases in alphabetical order.
	h) sudo make install ;;
	md) pandoc -s -o "$base".pdf "$file" ;;
    remark) "$dir"/remark/compile.sh "$file" ;;
    tex) pdflatex --shell-escape "$file" ;;
    bib) biber "$base" ;;
esac
