#!/bin/sh -eu

# Use diff-highlight to show word-level differences
# https://stackoverflow.com/a/39865453
diffhighlight="/usr/share/git/diff-highlight/diff-highlight"

diff -U3 --minimal "$@" |
  sed 's/^-/\x1b[1;31m-/;s/^+/\x1b[1;32m+/;s/^@/\x1b[1;34m@/;s/$/\x1b[0m/' |
  "$diffhighlight"
