#!/usr/bin/env sh
# add files or directories to fcd menu

INDEXFILE=~/.config/fcd/index.txt

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

for arg in "$@"
do
    realpath "$arg" | sed -E 's/^\/home\/[^\/]+/~/' >> "$INDEXFILE"
done

LANG=C sort "$INDEXFILE" -u -o "$INDEXFILE"
